/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnepagerV2RouteImport } from './routes/onepager-v2'
import { Route as OnepagerRouteImport } from './routes/onepager'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as IndexRouteImport } from './routes/index'

const OnepagerV2Route = OnepagerV2RouteImport.update({
  id: '/onepager-v2',
  path: '/onepager-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnepagerRoute = OnepagerRouteImport.update({
  id: '/onepager',
  path: '/onepager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRoute
  '/onepager': typeof OnepagerRoute
  '/onepager-v2': typeof OnepagerV2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRoute
  '/onepager': typeof OnepagerRoute
  '/onepager-v2': typeof OnepagerV2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/industries': typeof IndustriesRoute
  '/onepager': typeof OnepagerRoute
  '/onepager-v2': typeof OnepagerV2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/industries' | '/onepager' | '/onepager-v2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/industries' | '/onepager' | '/onepager-v2'
  id: '__root__' | '/' | '/industries' | '/onepager' | '/onepager-v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndustriesRoute: typeof IndustriesRoute
  OnepagerRoute: typeof OnepagerRoute
  OnepagerV2Route: typeof OnepagerV2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onepager-v2': {
      id: '/onepager-v2'
      path: '/onepager-v2'
      fullPath: '/onepager-v2'
      preLoaderRoute: typeof OnepagerV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onepager': {
      id: '/onepager'
      path: '/onepager'
      fullPath: '/onepager'
      preLoaderRoute: typeof OnepagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndustriesRoute: IndustriesRoute,
  OnepagerRoute: OnepagerRoute,
  OnepagerV2Route: OnepagerV2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
