/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as OnepagerV2RouteImport } from './routes/onepager-v2'
import { Route as OnepagerRouteImport } from './routes/onepager'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalLoginRouteImport } from './routes/portal.login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnepagerV2Route = OnepagerV2RouteImport.update({
  id: '/onepager-v2',
  path: '/onepager-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const OnepagerRoute = OnepagerRouteImport.update({
  id: '/onepager',
  path: '/onepager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/industries': typeof IndustriesRoute
  '/onepager': typeof OnepagerRoute
  '/onepager-v2': typeof OnepagerV2Route
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/login': typeof PortalLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/industries': typeof IndustriesRoute
  '/onepager': typeof OnepagerRoute
  '/onepager-v2': typeof OnepagerV2Route
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/login': typeof PortalLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/industries': typeof IndustriesRoute
  '/onepager': typeof OnepagerRoute
  '/onepager-v2': typeof OnepagerV2Route
  '/portal': typeof PortalRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/portal/login': typeof PortalLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/industries'
    | '/onepager'
    | '/onepager-v2'
    | '/portal'
    | '/sitemap.xml'
    | '/portal/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/industries'
    | '/onepager'
    | '/onepager-v2'
    | '/portal'
    | '/sitemap.xml'
    | '/portal/login'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/industries'
    | '/onepager'
    | '/onepager-v2'
    | '/portal'
    | '/sitemap.xml'
    | '/portal/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  IndustriesRoute: typeof IndustriesRoute
  OnepagerRoute: typeof OnepagerRoute
  OnepagerV2Route: typeof OnepagerV2Route
  PortalRoute: typeof PortalRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onepager-v2': {
      id: '/onepager-v2'
      path: '/onepager-v2'
      fullPath: '/onepager-v2'
      preLoaderRoute: typeof OnepagerV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onepager': {
      id: '/onepager'
      path: '/onepager'
      fullPath: '/onepager'
      preLoaderRoute: typeof OnepagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalLoginRoute: typeof PortalLoginRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLoginRoute: PortalLoginRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  IndustriesRoute: IndustriesRoute,
  OnepagerRoute: OnepagerRoute,
  OnepagerV2Route: OnepagerV2Route,
  PortalRoute: PortalRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
